version: "3"
services:
  postgresqls:
    container_name: "postgres-sqlalchemy"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POSTGRES_SQLALCHEMY
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_persdata:/var/lib/postgresql/data
    networks:
      - default
  pgadmin4:
    container_name: "pgadmin4-sqlalchemy"
    image: dpage/pgadmin4:latest
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@abc.com
      PGADMIN_DEFAULT_PASSWORD: password
    hostname: pgadmin4
    depends_on:
      - postgresqls
    restart: always
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    networks:
      - default
networks:
  default:
volumes:
  db_persdata:
  pgadmin4_volume:
